repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.286
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args: [--strict]
        exclude: "^test"
        additional_dependencies:
          - types-beautifulsoup4
          - types-tqdm
          - types-aiofiles
          - aiohttp
          - platformdirs

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: python
        pass_filenames: false
        always_run: true
        additional_dependencies:
          - bs4
          - pytest-asyncio
          - pytest-mock
          - pytest-vcr
          - aiohttp[speedups]
          - lxml
          - tqdm
          - platformdirs
          - mikan-card-downloader
          - aiofiles
