repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: "^test"

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        exclude: "^test"

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: "^test"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        args: [--strict]
        exclude: "^test"
        additional_dependencies:
          - types-beautifulsoup4
          - types-tqdm
          - aiohttp
          - platformdirs

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: python
        pass_filenames: false
        always_run: true
        additional_dependencies:
          - bs4
          - pytest-asyncio
          - pytest-mock
          - aiohttp
          - lxml
          - tqdm
          - platformdirs
