repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: "^test"

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        exclude: "^test"

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: "^test"

  - repo: https://github.com/DemonicSavage/pre-commit-pyright
    rev: 1.1.263
    hooks:
      - id: pyright
        exclude: "^test"

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: python
        pass_filenames: false
        always_run: true
        additional_dependencies:
          - bs4
          - pytest-asyncio
          - pytest-mock
          - aiohttp
          - lxml
          - tqdm
